[2024-09-21T22:33:08.239+0000] {processor.py:161} INFO - Started process (PID=6621) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:33:08.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:33:08.242+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:33:08.241+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:33:08.266+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:33:08.265+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:33:08.285+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:33:08.282+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 10, in <module>
    data.append(requests.get(f"https://api.openweathermap.org/data/2.5/weather?q={citie}&appid={api}").content.decode('utf-8'))
NameError: name 'requests' is not defined
[2024-09-21T22:33:08.286+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:33:08.302+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 0.068 seconds
[2024-09-21T22:33:38.885+0000] {processor.py:161} INFO - Started process (PID=6688) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:33:38.886+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:33:38.895+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:33:38.894+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:33:38.940+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:33:38.940+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:33:38.955+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:33:38.954+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 10, in <module>
    data.append(requests.get(f"https://api.openweathermap.org/data/2.5/weather?q={citie}&appid={api}").content.decode('utf-8'))
NameError: name 'requests' is not defined
[2024-09-21T22:33:38.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:33:38.987+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 0.112 seconds
[2024-09-21T22:34:06.616+0000] {processor.py:161} INFO - Started process (PID=6741) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:34:06.617+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:34:06.619+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:34:06.618+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:34:06.641+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:34:06.640+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:34:06.655+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:34:06.654+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 10, in <module>
    data.append(requests.get(f"https://api.openweathermap.org/data/2.5/weather?q={citie}&appid={api}").content.decode('utf-8'))
NameError: name 'requests' is not defined
[2024-09-21T22:34:06.656+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:34:06.671+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 0.059 seconds
[2024-09-21T22:34:22.298+0000] {processor.py:161} INFO - Started process (PID=6780) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:34:22.299+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:34:22.300+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:34:22.299+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:34:22.311+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:34:22.309+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 3, in <module>
    from airflow.models import requests
ImportError: cannot import name 'requests' from 'airflow.models' (/home/airflow/.local/lib/python3.8/site-packages/airflow/models/__init__.py)
[2024-09-21T22:34:22.311+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:34:22.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 0.060 seconds
[2024-09-21T22:34:52.683+0000] {processor.py:161} INFO - Started process (PID=6854) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:34:52.685+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:34:52.686+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:34:52.686+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:34:52.690+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:34:52.689+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 3, in <module>
    from airflow.models import requests
ImportError: cannot import name 'requests' from 'airflow.models' (/home/airflow/.local/lib/python3.8/site-packages/airflow/models/__init__.py)
[2024-09-21T22:34:52.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:34:52.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 0.041 seconds
[2024-09-21T22:34:53.764+0000] {processor.py:161} INFO - Started process (PID=6856) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:34:53.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:34:53.768+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:34:53.767+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:34:53.816+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:34:53.815+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:34:58.869+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:34:58.867+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 12, in <module>
    data_json_to_object = [json.loads(x) for x in data]
  File "/opt/airflow/dags/app/getWeatherData.py", line 12, in <listcomp>
    data_json_to_object = [json.loads(x) for x in data]
NameError: name 'json' is not defined
[2024-09-21T22:34:58.869+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:34:58.886+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 5.132 seconds
[2024-09-21T22:35:05.156+0000] {processor.py:161} INFO - Started process (PID=6871) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:35:05.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:35:05.162+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:35:05.161+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:35:05.194+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:35:05.194+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:35:10.208+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:35:10.207+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 13, in <module>
    data_json_to_object = [json.loads(x) for x in data]
  File "/opt/airflow/dags/app/getWeatherData.py", line 13, in <listcomp>
    data_json_to_object = [json.loads(x) for x in data]
NameError: name 'json' is not defined
[2024-09-21T22:35:10.209+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:35:10.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 5.077 seconds
[2024-09-21T22:35:20.310+0000] {processor.py:161} INFO - Started process (PID=6916) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:35:20.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:35:20.313+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:35:20.312+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:35:20.338+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:35:20.337+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:35:24.751+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:35:24.749+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 16, in <module>
    with open(f'raw_files/{datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}.json', 'w') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'raw_files/2024-09-21 22:35.json'
[2024-09-21T22:35:24.751+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:35:24.778+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 4.472 seconds
[2024-09-21T22:35:28.609+0000] {processor.py:161} INFO - Started process (PID=6928) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:35:28.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:35:28.612+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:35:28.611+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:35:28.628+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:35:28.628+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:35:34.091+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:35:34.090+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 16, in <module>
    with open(f'raw_files/{datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}.json', 'w') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'raw_files/2024-09-21 22:35.json'
[2024-09-21T22:35:34.093+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:35:34.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 5.506 seconds
[2024-09-21T22:35:45.918+0000] {processor.py:161} INFO - Started process (PID=6981) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:35:45.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:35:45.922+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:35:45.921+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:35:45.954+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:35:45.953+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:35:50.637+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:35:50.636+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 16, in <module>
    with open(f'app/raw_files/{datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}.json', 'w') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'app/raw_files/2024-09-21 22:35.json'
[2024-09-21T22:35:50.637+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:35:50.650+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 4.737 seconds
[2024-09-21T22:36:15.539+0000] {processor.py:161} INFO - Started process (PID=7045) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:36:15.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:36:15.542+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:36:15.542+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:36:15.565+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:36:15.564+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:36:20.660+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:36:20.659+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 16, in <module>
    with open(f'/raw_files/{datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}.json', 'w') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/raw_files/2024-09-21 22:36.json'
[2024-09-21T22:36:20.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:36:20.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 5.141 seconds
[2024-09-21T22:36:51.367+0000] {processor.py:161} INFO - Started process (PID=7115) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:36:51.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:36:51.370+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:36:51.369+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:36:51.392+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:36:51.392+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:36:56.174+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:36:56.173+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 16, in <module>
    with open(f'/raw_files/{datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}.json', 'w') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/raw_files/2024-09-21 22:36.json'
[2024-09-21T22:36:56.175+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:36:56.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 4.827 seconds
[2024-09-21T22:37:01.279+0000] {processor.py:161} INFO - Started process (PID=7128) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:37:01.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:37:01.282+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:37:01.281+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:37:01.301+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:37:01.300+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:37:06.571+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:37:06.569+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 16, in <module>
    with open(f'raw_files/{datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}.json', 'w') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'raw_files/2024-09-21 22:37.json'
[2024-09-21T22:37:06.571+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:37:06.588+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 5.314 seconds
[2024-09-21T22:37:36.965+0000] {processor.py:161} INFO - Started process (PID=7207) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:37:36.967+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:37:36.968+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:37:36.968+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:37:36.988+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:37:36.988+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:37:41.859+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:37:41.857+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 16, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'raw_files/2024-09-21 22:37.json'
[2024-09-21T22:37:41.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:37:41.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 4.914 seconds
[2024-09-21T22:38:12.065+0000] {processor.py:161} INFO - Started process (PID=7288) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:38:12.069+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:38:12.071+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:38:12.070+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:38:12.086+0000] {logging_mixin.py:188} INFO - /opt/airflow
[2024-09-21T22:38:12.109+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:38:12.109+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:38:17.671+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:38:17.670+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 17, in <module>
    with open(f'raw_files/{datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}.json', 'w') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'raw_files/2024-09-21 22:38.json'
[2024-09-21T22:38:17.673+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:38:17.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 5.645 seconds
[2024-09-21T22:38:47.849+0000] {processor.py:161} INFO - Started process (PID=7372) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:38:47.851+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:38:47.852+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:38:47.852+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:38:47.854+0000] {logging_mixin.py:188} INFO - /opt/airflow
[2024-09-21T22:38:47.869+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:38:47.868+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:38:52.224+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:38:52.223+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 17, in <module>
    with open(f'raw_files/{datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}.json', 'w') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'raw_files/2024-09-21 22:38.json'
[2024-09-21T22:38:52.225+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:38:52.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 4.403 seconds
[2024-09-21T22:39:23.013+0000] {processor.py:161} INFO - Started process (PID=7449) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:39:23.015+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:39:23.016+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:39:23.016+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:39:23.020+0000] {logging_mixin.py:188} INFO - /opt/airflow
[2024-09-21T22:39:23.050+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:39:23.049+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:39:27.594+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:39:27.593+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app/getWeatherData.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app/getWeatherData.py", line 17, in <module>
    with open(f'raw_files/{datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}.json', 'w') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'raw_files/2024-09-21 22:39.json'
[2024-09-21T22:39:27.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:39:27.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 4.604 seconds
[2024-09-21T22:39:55.493+0000] {processor.py:161} INFO - Started process (PID=7516) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:39:55.495+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:39:55.496+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:39:55.496+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:39:55.500+0000] {logging_mixin.py:188} INFO - /opt/airflow
[2024-09-21T22:39:55.526+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:39:55.526+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:40:01.444+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:40:01.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 5.975 seconds
[2024-09-21T22:40:31.597+0000] {processor.py:161} INFO - Started process (PID=7593) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:40:31.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:40:31.604+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:40:31.604+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:40:31.607+0000] {logging_mixin.py:188} INFO - /opt/airflow
[2024-09-21T22:40:31.643+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:40:31.642+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:40:36.267+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:40:36.275+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 4.687 seconds
[2024-09-21T22:40:49.230+0000] {processor.py:161} INFO - Started process (PID=7639) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:40:49.230+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:40:49.231+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:40:49.231+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:40:49.234+0000] {logging_mixin.py:188} INFO - /opt/airflow
[2024-09-21T22:40:49.253+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:40:49.253+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:40:54.013+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:40:54.022+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 4.796 seconds
[2024-09-21T22:41:24.712+0000] {processor.py:161} INFO - Started process (PID=7717) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:41:24.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:41:24.716+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:41:24.715+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:41:24.718+0000] {logging_mixin.py:188} INFO - /opt/airflow
[2024-09-21T22:41:24.741+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:41:24.740+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:41:29.476+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:41:29.485+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 4.777 seconds
[2024-09-21T22:41:59.852+0000] {processor.py:161} INFO - Started process (PID=7792) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:41:59.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:41:59.857+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:41:59.857+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:41:59.865+0000] {logging_mixin.py:188} INFO - /opt/airflow
[2024-09-21T22:41:59.910+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:41:59.910+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:42:05.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:42:05.012+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 5.169 seconds
[2024-09-21T22:42:35.614+0000] {processor.py:161} INFO - Started process (PID=7863) to work on /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:42:35.616+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app/getWeatherData.py for tasks to queue
[2024-09-21T22:42:35.617+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:42:35.617+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:42:35.620+0000] {logging_mixin.py:188} INFO - /opt/airflow
[2024-09-21T22:42:35.648+0000] {logging_mixin.py:188} INFO - [2024-09-21T22:42:35.647+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-09-21T22:42:40.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app/getWeatherData.py
[2024-09-21T22:42:40.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app/getWeatherData.py took 4.453 seconds
